### PR TITLE
Modify git config

### PR DESCRIPTION
**Pull request by tobson**
@wdobler Should the scripts under `utils/git/bin` that are called whenever `make` is run perhaps check if Git is actually installed?

### CODE REVIEW

**Comment by tobson** [comment]
@PABourdin It turns out that git-rebase is just a [shell script](https://github.com/git/git/blob/master/git-rebase.sh). I created a new script `utils/git/bin/git-up.sh` that inherits all the autostash logic from the original Git source. In order to invoke this with `git up`, run

```
git config --local alias.up '!'"$PENCIL_HOME/utils/git/bin/git-up.sh"
```

Can you please test if this works on CentOS 6?

**Comment by PABourdin** [comment]
@tobson I am very much in favour of our previous (longer) purely GIT- and alias-based solution, without relying on $PENCIL_HOME. This would also work without having executed ". sourceme.sh" and would therefore also work immediately, even before you have tried to compile/start/run anything.

I have in the mean time btw. realized that we need not to "git stash apply" with a given name! This is because the latest stash must be from the "git stash save" that appears earlier in the command sequence. (= Same argument why we can do a simple "git stash drop".)

EDIT: Sorry, no, that only applies when a stash has been created! Otherwise we would apply something else we might not want to apply... :-/

Does this solution not work for CentOS 6?
Regarding CentOS 6: I have already updated all machines in our institute's clusters to 7.3.

**Comment by tobson** [comment]
I agree that the reliance on $PENCIL_HOME is a drawback, but it's liberally
the only one. Maybe a best-of-both worlds solution can be found. The
autostash logic copied verbatim from the Git source code is almost
certainly more robust.

But hey, I'm not gonna use this alias anyway, so I'm not gonna fight this.

**Comment by tobson** [comment]
The best-of-both-worlds solution likely being Wolfgang's proposed 'git pc
pull-and-rebase'

**Comment by tobson** [comment]
Actually, I'm gonna counterargue a little...

> I have in the mean time btw. realized that we need not to "git stash
> apply" with a given name! This is because the latest stash must be from the
> "git stash save" that appears earlier in the command sequence. (= Same
> argument why we can do a simple "git stash drop".)

What if a user does _not_ have any uncommitted changes but _does_ have some
things in the stash that she never dropped and forgot about. In that case,
"git stash save" wouldn't do anything, but "git stash apply" would apply
the forgotten stash!

"git rebase --autostash" obviously avoids this undesirable behavior and so
does utils/git/bin/git-up.sh

**Comment by tobson** [comment]
> Regarding CentOS 6: I have already updated all machines in our
> institute's clusters to 7.3.

Good for you! You were the one who insisted on compatibility with CentOS
6...

**Comment by PABourdin** [comment]
@tobson 

> You were the one who insisted on compatibility with CentOS 6...

I insisted in supporting git version 1.8.3.1+, which is CentOS 7 (implies supporting ubuntu 14.04 LTS).
Since recently, that version may be 1.8.4.something, as you found out.

But indeed I agree that supporting CentOS 6 is a requirement, too, because these systems are not at their end-of-life and we must expect users coming across such systems. E.g., St. Andrews University recently still ran CentOS 6 on some of their MHD group's most powerful servers.

And yes, in my edit above I already realized that the "git stash apply" requires the given name.

We tested that this one-line alias worked on git 1.8.3.1, so when we can avoid depending on $PENCIL_HOME, I would strongly suggest to avoid that. (Because I can already anticipate what will otherwise happen for myself and other PC users.)

The only missing feature in our one-line alias would be that you may run it within only one subdirectory or for a given filename (similar to "svn up"). But that is of secondary priority.

**Comment by tobson** [comment]
I agree that CentOS 6 let alone 7 are not old enough to be ignored.

To summarize: `rebase --autostash` exists since Git 1.8.4 (see the [changelog](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/1.8.4.txt)), CentOS 7 has [Git 1.8.3.1](http://mirror.centos.org/centos/7/os/x86_64/Packages/git-1.8.3.1-5.el7.x86_64.rpm), and CentOS 6 has [Git 1.7.1](http://mirror.centos.org/centos/6/os/x86_64/Packages/git-1.7.1-4.el6_7.1.x86_64.rpm). So we need a workaround.

> We tested that this one-line alias worked on git 1.8.3.1, so when we can avoid depending on $PENCIL_HOME, I would strongly suggest to avoid that. (Because I can already anticipate what will otherwise happen for myself and other PC users.)

What is it that will happen? I'm just asking out of curiosity.

**Comment by PABourdin** [comment]
E.g. wrongly set or unset PENCIL_HOMEs, outdated code in diverse PENCIL_HOME versions that are still used for reproducing old stuff (which summarizes to "frustration due to unintended user error").

But not to forget also a simple bisect would bring you into a situation where all of a sudden the script referenced in the alias disappeared ("frustration without the user being at fault").

**Comment by tobson** [comment]
@PABourdin @wdobler I believe the essence of `git pull --rebase --autostash` is captured by the sequence of commands

``` sh
sha1=$(git stash create "autostash")
[ -n "$sha1" ] && git reset --hard
git pull --rebase
[ -n "$sha1" ] && git stash apply "$sha1" && git gc --auto
```

In 8b18226 I defined alias.up to be the corresponding one-liner. The above code is essentially copied from [here](https://github.com/git/git/blob/master/git-rebase.sh) and its big advantage is that by using `git stash create`, there is zero interference with what may or may not be in the user's stash, see `git help stash`.

I've put up a screencast that illustrates the `git up` workflow [here](https://asciinema.org/a/d75bp290jm7sogt4x3mpvb18x). I've tested this with Git 1.7.1 (i.e. RHEL 6's version).

**Comment by wdobler** [comment]
I think the 'git gc' will block with older git versions, so I'd leave it out.
[In the current git source code, the situation is different, in that they know their git-gc version works in the background.]

**Comment by tobson** [comment]
It's my understanding that the `--auto` flag exists so that `git gc` can be run "just in case" as it usually doesn't actually perform any work. For instance, `git merge` seems to be running `git gc --auto` every time in v1.7.1, see [merge.c](https://github.com/git/git/blob/v1.7.1/builtin/merge.c#L353).

**Comment by tobson** [comment]
I've put up another [screencast](https://asciinema.org/a/f4qbsjye95qhoodkus2wdiihc) that shows what to do if `git up` results in a conflict.

**Pull request closed without merging**
